steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'docker/${_IMAGE}/Dockerfile', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', '${_IMAGE}', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_TAG}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_TAG}']

substitutions:
  _PROJECT_ID: "protocell-404013"
  _REGION: "europe-central2"
  _REPOSITORY: "kubeflow-images"
  _IMAGE: 'keras'
  _IMAGE_TAG: 'keras:latest'

