steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'docker/${_IMAGE}/Dockerfile', '-t', '${_IMAGE}', '.']

  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
    - -c
    - |
      apt-get install -qq jq -y &&
      source scripts/json2env.sh "$${CONFIGS}" &&
      docker tag ${_IMAGE} ${location}-docker.pkg.dev/${project}/${dockfactory}/${_IMAGE}:${_IMAGE_TAG}
    secretEnv: ['CONFIGS']

  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
    - -c
    - |
      apt-get install -qq jq -y &&
      source scripts/json2env.sh "$${CONFIGS}" &&
      docker push ${location}-docker.pkg.dev/${project}/${dockfactory}/${_IMAGE}:${_IMAGE_TAG}
    secretEnv: ['CONFIGS']

substitutions:
  _IMAGE: 'keras'
  _IMAGE_TAG: 'latest'

availableSecrets:
  secretManager:
  - versionName: "projects/protocell-404013/secrets/protocell-config/versions/latest"
    env: 'CONFIGS'

options:
  logging: CLOUD_LOGGING_ONLY